### ISSUE TITLE
New Logo/Icon Design For Quest

### ISSUE THREAD

**Issue by zularizal** [calvin-li/Quest#2]
Hi @calvin-li , I am a graphic designer. I have seen your launcher icon app. I think your icon is not relevant to your project. Therefore, I want to contribute by creating a new logo/icon for you. How do you think?

**Comment by calvin-li** [comment]
Hi @zularizal, you're welcome to contribute if you really want to, but there's no money involved in the app so you won't be paid for it

**Comment by zularizal** [comment]
Of course, you don't need to pay for this.

Can you provide a description of this app?

If possible, can you send the main view of this app?

I need this data to design the logo.

Thanks.

**Comment by calvin-li** [comment]
Here's the play store link for the app. It has a few pictures, if you have
an android phone you can download it and take a look.
https://play.google.com/store/apps/details?id=com.sandbox.calvin_li.quest

**Comment by zularizal** [comment]
This logo is inspired by the letter Q, Kompas and track.
I designed this new logo and icon in a simple, elegant, relevant and modern style.
I created this logo so as not to disappear the old logo character. So that existing users are familiar with this new logo.

What do you think?
If something wants to be changed, let me know.

![bitmap](https://user-images.githubusercontent.com/38547278/46816609-8df9f000-cda7-11e8-8930-6a524c407c49.png)

**Comment by calvin-li** [comment]
Looks good initially, can you create a pull request to replace the old icon with the new one?
The icon files are under `Quest/app/resources/`, with a copy of the PNG in `Quest/app/src/main/res/mipmap-xxxhdpi/`. I'll probably reorganize the folder structure a bit and put all the icon files under their own folder.

Also, we'll need an icon for the notifications specifically. They [have a specific size and style](https://developer.android.com/guide/practices/ui_guidelines/icon_design_status_bar#size11). Basically, they are small (48x48) and need to be white with a transparent background. You will probably have to do more than just scaling down the launcher icon.

**Comment by zularizal** [comment]
Hi, I have added the logo, launcher icon, and status bar icon along with the vector file to the drive.

https://drive.google.com/open?id=1AqANoJ3AJ1Knrl23pEHM6eng5uT0Q-bi

And also I have sent a pull request to you. #3

**Comment by calvin-li** [comment]
Sorry, I've been busy with work, should be able to take a look tonight

**Comment by calvin-li** [comment]
Just updated the app on the play store

**Comment by calvin-li** [comment]
Just updated the app on the play store. Let me know if the release notes look good.
